### ISSUE TITLE
Questions regarding paper

### ISSUE THREAD

**Issue by rcywongaa** [bernhardpg/planning-through-contact#101]
Hello,

Thanks for the fascinating paper and for making the code available!
I am quite intrigued by how you tightened the relaxation as described in VII.D Additional remarks.
I'd like to ask the following questions:

1. What was the movitation behind the tightening procedure?  Did it return trivial solutions without them?  How did this tightening impact performance (in terms of solve time and success rate)?
2. My understanding is that you employed the following procedures to achieve the tightening:
   1. Multiplying the linear constraints together
   2. Using the rotation formulation in (16) to generate additional constraints
       1. Formulate constraint (8) in both world and slider frame
       2. Formulate initial and target rotations

   Am I right to say that (i) and (ii) are unrelated, and that only (i) is related to the moment-SOS hierarchy?
3. Could you share the intuition / thought process behind this specific choice of tightening constraints?  Was it  "obvious" that these seemingly redundant constraints would generate different constraints in the SDP relaxation?  Were there more such constraints that ended up being unnecessary or that you didn't pursue?

Thanks again for the paper and code!

Best regards,
Rufus

**Comment by rcywongaa** [comment]
Hi Bernhard,

Thanks a lot for the reply!  I'm looking into using similar methods to tighten relaxations, your paper, code and clarifications is of immense help, thanks again!

**Comment by bernhardpg** [comment]
@rcywongaa no problem, happy to help!
